### ISSUE TITLE
libavformat/avformat.h file not found

### ISSUE THREAD

**Issue by usingsystem8** [lvjian700/ffmpegc-demo#1]
I ran this project, but an error occurred.
In VideoFrameExtractor.h on line 25, "libavformat/avformat.h file not found".
Could you tell me how to run this project?

**Comment by lvjian700** [comment]
You can read this blog :
http://witcheryne.iteye.com/blog/1734706

**Comment by usingsystem8** [comment]
I have read this blog, but I get error yet.
I'll try to compile ffmpeg again.

**Comment by usingsystem8** [comment]
Do I have to compile ffmpegc?
I tried to compile ffmpegc, but following errors occurred.

make: **\* [libavcodec/h264_cabac.o] Error 1
cp: ./libavcodec/libavcodec.a: No such file or directory
cp: ./libavutil/libavutil.a: No such file or directory
cp: ./libswscale/libswscale.a: No such file or directory
lipo: can't open input file: ./build/i386/libavcodec.a (No such file or directory)
lipo: can't open input file: ./build/i386/libavutil.a (No such file or directory)
lipo: can't open input file: ./build/i386/libswscale.a (No such file or directory)

I'm sorry to bother you again.

**Comment by usingsystem8** [comment]
And in build directory, there are only 2 directories and 3 files.
armv7,i386,libavdevice.a,libavfilter.a,libavformat.a

**Comment by usingsystem8** [comment]
I SOLVED it by myself.
I succeeded to build in ios simulator, but I didn't succeed to build in my iPod Touch.
Finally, I found that I was using libraries for simulator (i386).
Thank you.

**Comment by speedoholic** [comment]
@lvjian700 @usingsystem8  The issue still exists when trying to build for a device (armv7)
